---
format: 
  html:
    theme: meds-website-styles.scss
    toc: true
    toc-location: left
    toc-depth: 3
    smooth-scroll: true
---

## {{< fa code title="code" >}} Let's write & run some Python code {#code}

### Exercise 1: Running existing Python code
Sometimes you'll receive Python code and an environment file (environment.yml or requirements.txt) from a collaborator. In this exercise, you will reproduce an environment and run a Python script. 

- Download the [`environment.yml`](https://github.com/UCSB-MEDS/intro-to-python/blob/main/exercises/environment.yml){target="_blank"}  and [intro-to-python.ipynb](https://github.com/UCSB-MEDS/intro-to-python/blob/main/exercises/intro-to-python.ipynb){target="_blank"} from GitHub and save them to your project directory.


::: {.callout-note collapse="true"}
## environment.yml

The `environment.yml` is a text file that specifies a conda environment's name, channels to download from, and package dependencies. It is similar to a `requirements.txt` file that is used for `venv`.
```{yaml}
name: cmip6-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - intake
  - intake-esm
  - s3fs
  - xarray
  - zarr
  - matplotlib
  - numpy
  - pandas
  - jupyter
  - ipykernel
```
:::

To download the Python environment and Jupyter Notebook in the Terminal, you can run the following:
```{bash filename="Terminal"}
#| eval: false
#| echo: true

# Download the environment.yml
curl -O https://raw.githubusercontent.com/UCSB-MEDS/intro-to-python/main/exercises/environment.yml

# Download the intro-to-python.ipynb notebook
curl -O https://raw.githubusercontent.com/UCSB-MEDS/intro-to-python/main/exercises/intro-to-python.ipynb
```


- Create the `cmip6-env` conda environment from a file, which in this case is called `environment.yml`:

```{bash filename="Terminal"}
#| eval: false
#| echo: true
conda env create -f environment.yml
```

- Activate the environment:

```{bash filename="Terminal"}
#| eval: false
#| echo: true
conda activate cmip6-env
```

- Register `cmip6-env` as a Jupyter kernel so it's available as a notebook interpreter:

```{bash filename="Terminal"}
#| eval: false
#| echo: true
python -m ipykernel install --user --name cmip6-env --display-name "Python (cmip6-env)"
```


- In Positron, open `intro-to-python.ipynb`. Select `cmip6-env` as your interpreter by clicking the interpreter selector in the top right of the Jupyter Notebook and choosing `Python (cmip6-env)`. 

- Run through all the cells in the Jupyter Notebook.

### Exercise 2: Translating R to Python

Let's say you already have some R code for reproducing the [US Drought Monitor](https://droughtmonitor.unl.edu/){target="_blank"}'s ["Drought area in California" visualization](https://en.wikipedia.org/wiki/Droughts_in_California#/media/File:Drought_area_in_California.svg){target="_blank"} (you can download the necessary data from [Google Drive](https://drive.google.com/file/d/1SQOUoCD9RZIpzm2rKyjKenRlMFiCKhny/view?usp=sharing){target="_blank"}), and you'd like to translate it to Python:

::: {.callout-note collapse="true"}
## Expand for R code
```{r}
#| eval: false
#| echo: true
#| message: false
#| warning: false
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                                    setup                                 ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#..........................load packages.........................
library(tidyverse)

#..........................import data...........................
drought <- read_csv(here::here("data", "drought.csv"))

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##                            wrangle drought data                          ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean <- drought |>
  
  # pivot table to be in tidy form ----
  pivot_longer(cols = None:D4, names_to = "drought_lvl", values_to = "area_pct") |>
  
  # clean up col names ----
  janitor::clean_names() |>
  
  # Rename state abbreviation column ----
   rename(state_abb = state_abbreviation) |>

  # select cols of interest & update names for clarity (as needed) ----
  select(date = valid_start, state_abb, drought_lvl, area_pct) |> 

  # add drought level conditions names ---- 
  mutate(drought_lvl_long = factor(drought_lvl,
                                   levels = c("D4", "D3", "D2", "D1","D0", "None"),
                                   labels = c("D4 (Exceptional)", "D3 (Extreme)",
                                       "D2 (Severe)", "D1 (Moderate)", 
                                       "D0 (Abnormaly Dry)", 
                                       "No Drought"))) |>
  
  # reorder cols ----
  relocate(date, state_abb, drought_lvl, drought_lvl_long, area_pct)

##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##       create stacked area plot of CA drought conditions through time     ----
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drought_clean |> 
  
  # remove drought_lvl "None" & filter for just CA ----
  filter(drought_lvl != "None",
         state_abb == "CA") |> 
  
  # initialize ggplot ----
  ggplot(mapping = aes(x = date, y = area_pct, fill = drought_lvl_long)) +
  
  # reverse order of groups so level D4 is closest to x-axis ----
  geom_area(position = position_stack(reverse = TRUE)) +
  
  # update colors to match US Drought Monitor ----
  # (colors identified using ColorPick Eyedropper extension on the original USDM data viz) 
  scale_fill_manual(values = c("#853904", "#FF0000", "#FFC100", "#FFD965", "#FFFF00")) +
  
  # set x-axis breaks & remove padding between data and x-axis ----
  scale_x_date(breaks = scales::breaks_pretty(n = 13),
               limits = as.Date(c("2000-01-01", "2026-12-31")),
               expand = c(0,0)) +

  # set y-axis breaks & remove padding between data and y-axis & convert values to percentages ----
  scale_y_continuous(breaks = seq(0, 100, by = 10),
                     expand = c(0, 0),
                     labels = scales::label_percent(scale = 1)) +
  
  # add title ----
  labs(title = "Drought area in California") +

  # set theme minimal (includes major/minor grid lines, no axes) ----
  theme_minimal() +
  
  # fine-tune adjustments to plot theme ----
  theme(
    
    # update axis lines & ticks color ----
    axis.line = element_line(color = "#5A9CD6"),
    axis.ticks = element_line(color = "#5A9CD6"),
    
    # adjust length of axis ticks ----
    axis.ticks.length = unit(.2, "cm"),
    
    # center plot title ----
    plot.title = element_text(hjust = 0.5, color = "#686868", size = 20,
                              margin = margin(t = 10, r = 0, b = 15, l = 0)),
    
    # remove axis & legend titles ----
    axis.title = element_blank(),
    legend.title = element_blank(),
    
    # axis text color & size ----
    axis.text = element_text(color = "#686868", size = 10),
    legend.text = element_text(color = "#686868", size = 10),
    
    # move legend below plot ----
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.key.width = unit(0.4, "cm"),
    legend.key.height = unit(0.25, "cm"),
    
    # update plot background color & plot margins ----
    plot.background = element_rect(color = "#686868"),
    plot.margin = margin(t = 10, r = 40, b = 10, l = 40)
  )
```
:::

::: {.callout-important}
## which approach should we recommend? export environment or create environment.yml first?
:::

1. **Start by creating a new `conda` environment from scratch:**

- In your Positron Terminal, create an environment named `drought-env`

```{bash filename="Terminal"}
#| eval: false
#| echo: true
conda create -n drought-env python=X
```

- Activate your `drought-env` environment:

```{bash filename="Terminal"}
#| eval: false
#| echo: true
conda activate drought-env
```

- Install the necessary packages to your `drought-env` from the `conda-forge` channel (reminder: [conda-forge](https://conda-forge.org/docs/user/introduction/){target="_blank"} is a large repository of community-maintained Python packages):

```{bash filename="Terminal"}
#| eval: false
#| echo: true
conda install -c conda-forge pandas plotnine
```

- Optionally, export your envrionment so that others who may use your code can reproduce your environment:

```{bash filename="Terminal"}
#| eval: false
#| echo: true
# exports all currently installed packages and versions
conda env export > environment.yml 

# alternatively: only include packages that you explicitly installed, not their dependencies (more portable)
conda env export --from-history > environment.yml
```