name: cmip6-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - intake
  - intake-esm
  - s3fs
  - xarray
  - zarr
  - matplotlib
  - numpy
  - pandas
  - jupyter
  - ipykernel
